name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'
  schedule:
    # test master every day at 04:00 UTC
      - cron: '0 4 * * *'

jobs:
  build:
    # the OS must be GNU/Linux to be able to use the docker-coq-action
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - 'coqorg/coq:dev'
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      # TODO - uses: coq-community/docker-coq-action@v1
      - uses: coq-community/docker-coq-action@staging
        with:
          opam_file: 'coq-bignums.opam'
          custom_image: ${{ matrix.image }}
          after_script: |
            : Workaround permission issue
            sudo chown -R coq:coq .
            : Run tests
            make -C tests
      - name: Revert permissions
        if: ${{ always() }}
        run: sudo chown -R 1001:116 .

# See also:
# https://github.com/coq-community/docker-coq-action#readme
# https://github.com/erikmd/docker-coq-github-action-demo
